---
driver:
  name: vagrant
  driver_config:
    require_chef_omnibus: latest

provisioner:
  name: chef_zero
  data_path: test/shared
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: debian-8.7.1-amd64
  driver_config:
    box: debian-8.7.1-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/boxes/debian-8.7.1-amd64/versions/1.0.45/providers/virtualbox.box

- name: ubuntu-16.04.2-server-amd64
  driver_config:
    box: ubuntu-16.04.2-server-amd64
    box_url: https://atlas.hashicorp.com/ffuenf/boxes/ubuntu-16.04.2-server-amd64/versions/1.0.45/providers/virtualbox.box

suites:
- name: default
  run_list:
    - recipe[automysqlbackup::default]
  attributes: {}